### ISSUE TITLE
misc.get_sessions_by_mac - AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by oianson** [CiscoISE/ciscoisesdk#4]
Hello,

When I am trying to use the following script to get_sessions_by_mac, I am getting `AttributeError: 'str' object has no attribute 'get'`

```
lab.misc.get_sessions_by_mac('00:50:56:8F:78:4F').response
```

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    bwi.misc.get_sessions_by_mac('00:50:56:8F:78:4F').response
  File "/home/ubuntu/ciscoisesdk/ciscoisesdk/api/v3_0_0/misc.py", line 408, in get_sessions_by_mac
    _api_response = self._session.get(endpoint_full_url, params=_params)
  File "/home/ubuntu/ciscoisesdk/ciscoisesdk/restsession.py", line 426, in get
    response = self.request('GET', url, erc, 0, params=params, **kwargs)
  File "/home/ubuntu/ciscoisesdk/ciscoisesdk/restsession.py", line 350, in request
    check_response_code(response, erc)
  File "/home/ubuntu/ciscoisesdk/ciscoisesdk/utils.py", line 217, in check_response_code
    raise ApiError(response)
  File "/home/ubuntu/ciscoisesdk/ciscoisesdk/exceptions.py", line 151, in __init__
    if self.details else None
AttributeError: 'str' object has no attribute 'get'
```

When I do this API call manually I get back an HTTP 500 error 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mnt-rest-result>
    <http-code>500</http-code>
    <cpm-code>34110</cpm-code>
    <description>Server has encountered error while processing the REST request</description>
    <module-name>MnT</module-name>
    <internal-error-info>Error in generating XML output. Error message = Session data is not available for AA:BB:CC:DD:EE:FF.</internal-error-info>
    <requested-operation>Get By Type</requested-operation>
    <resource-id>N/A</resource-id>
    <resource-name>N/A</resource-name>
    <resource-type>RESTSDStatus</resource-type>
    <status>SERVER_ERROR</status>
</mnt-rest-result>
```

I believe this might be the problem as when I use a MAC address which has a session, I get a response as expected

**Comment by wastorga** [comment]
Hello @oianson.

Thank you for reporting the issue and a possible solution.

I will need to check the behavior of the other responses to see if the `message` property change makes sense for other MNT operations.

**Comment by steinzi** [comment]
Having the same issue, 
Running the 1.0 version and everything is updated.

**Comment by wastorga** [comment]
Sorry for the delay. In the last version we made some changes to how we get the `message` property for `exceptions.py`.

It should be ok now.
